### ISSUE TITLE
Element class

### ISSUE THREAD

**Issue by 17kpatrick** [bpsullivan3/CSC8540_PeriodicTable#1]
Hello,

I've started work on the interface and here are some of the methods which we will need so far from the Element class.

String getPhoto() - This will return a string in the format "images/hydrogen_image.png" with hydrogen being replaced with whatever the element the image belongs to. This is probably the least important thing to work on right now as I already have a placeholder image for the elements and it will take some time for us to actually gather the images.

String getAtomicNumber()
String getMeltingPoint()
String getBoilingPoint()
String getDescription()

These methods are all strings because they need to be strings to go into a text fields, which is how they are displayed, and if we need to do math we can just use a wrapper to get the integer or double values.

The hardest part of this is just going to be the tediousness of getting all of the information. If you have any suggestions of more things which should be added to the element overview panel let me know and I will add a location for it.

Thanks,
Kyle

**Comment by 17kpatrick** [comment]
Something else I thought about are booleans like isNobleGas as well as integers like metalType (0 for metal, 1 for metalloid, 2 for non-metal) which we will need to use later for filtering.

**Comment by bpsullivan3** [comment]
Element Class created to handle mentioned methods.
