### ISSUE TITLE
Use Case, Sequence, and Class Diagrams

### ISSUE THREAD

**Issue by 17kpatrick** [bpsullivan3/CSC8540_PeriodicTable#2]
[Basic Use Case Diagram.pdf](https://github.com/bpsullivan3/CSC8540_PeriodicTable/files/2406506/Basic.Use.Case.Diagram.pdf)
[Basic Sequence Diagram.pdf](https://github.com/bpsullivan3/CSC8540_PeriodicTable/files/2406507/Basic.Sequence.Diagram.pdf)

I attached the Use Case and Sequence Diagrams for you to look over. We still need to make the class diagram once all of our classes are designed and submit all of these by next Thursday. Let me know what you think of the diagrams.

**Comment by bpsullivan3** [comment]
Reviewed and approved.
